# Generated by Django 4.1.5 on 2023-02-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0003_banner_image_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner_image',
            name='category',
            field=models.CharField(choices=[('shoes', 'shoes'), ('fashions', 'fashions'), ('mobiles', 'mobiles'), ('laptops', 'laptops')], max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'shoes'), ('fashions', 'fashions'), ('mobiles', 'mobiles'), ('laptops', 'laptops')], max_length=255),
        ),
    ]
