# Generated by Django 4.1.5 on 2023-02-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0004_alter_banner_image_category_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(upload_to='')),
                ('user', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='wishlist',
        ),
    ]
