# Generated by Django 4.1.5 on 2023-02-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0005_wishlist_remove_product_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
