# Generated by Django 4.1.5 on 2023-02-27 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0006_wishlist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewApp.category'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='price',
            field=models.FloatField(),
        ),
    ]
