# Generated by Django 4.1.5 on 2023-02-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0007_alter_product_category_alter_wishlist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'shoes'), ('fashions', 'fashions'), ('mobiles', 'mobiles'), ('laptops', 'laptops')], max_length=255),
        ),
    ]
