# Generated by Django 4.1.5 on 2023-02-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0011_alter_cart_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
