# Generated by Django 4.1.5 on 2023-02-27 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0014_alter_wishlist_category_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner_image',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewApp.category'),
        ),
    ]
