# Generated by Django 4.1.5 on 2023-02-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0016_remove_cart_name_remove_cart_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
